# https://cloud.google.com/cloud-build/docs/build-config?hl=ja
steps:
  # Permission
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: permission
    args:
      - init
  # Switch Workspace
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: permission
    args:
      - workspace
      - select
      - $_ENVIRONMENT
      - -no-color
  # Plan
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: permission
    args:
      - plan
      - -out=tfplan
      - -no-color
  # Apply
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: permission
    args:
      - apply
      - tfplan
      - -no-color
  # Backend
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: backend
    args:
      - init
  # Switch Workspace
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: backend
    args:
      - workspace
      - select
      - $_ENVIRONMENT
      - -no-color
  # Plan
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: backend
    args:
      - plan
      - -out=tfplan
      - -no-color
  # Apply
  - name: hashicorp/terraform:0.12.24
    entrypoint: terraform
    dir: backend
    args:
      - apply
      - tfplan
      - -no-color
